/* This file autogenerated by src/common/Makefile */
char *default_plugin_path = "/opt/slurm/lib/slurm";
char *default_slurm_config_file = "/opt/slurm/etc/slurm.conf";
char *default_plugstack = "/opt/slurm/etc/plugstack.conf";
